# Generated by Django 2.1.5 on 2020-09-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=250)),
                ('nationality', models.PositiveSmallIntegerField(choices=[(1, 'American'), (2, 'French'), (3, 'Chinese'), (4, 'Thai'), (5, 'Indian'), (6, 'Pakistani'), (8, 'Italian'), (9, 'Japanese'), (10, 'Korean'), (11, 'Afghani'), (12, 'Arabian')], default=1)),
                ('no_of_serving', models.PositiveSmallIntegerField()),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Fast Food'), (2, 'Savoury'), (3, 'Dessert'), (4, 'Breakfast'), (5, 'Lunch'), (6, 'Dinner')], default=1)),
                ('glutten_free', models.BooleanField(default=False)),
                ('customizable', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='dishes/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'American'), (2, 'French'), (3, 'Chinese'), (4, 'Thai'), (5, 'Indian'), (6, 'Pakistani'), (8, 'Italian'), (9, 'Japanese'), (10, 'Korean'), (11, 'Afghani'), (12, 'Arabian')])),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='dishes/%Y/%m/%d')),
            ],
        ),
    ]
